/**
 * EterX Agent — Model Provider Registry
 * All supported AI model providers with their config, endpoints, env keys, and npm packages.
 */

const PROVIDERS = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    envKeys: ['GEMINI_API_KEY'],
    multiKey: true,
    maxKeys: 30,
    envPrefix: 'GEMINI_API_KEY_',
    npm: ['@google/genai'],
    getUrl: 'https://aistudio.google.com/apikey',
    models: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.0-flash'],
    required: true,
    description: 'Primary engine. Free tier available. Supports load-balanced key pools.',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    envKeys: ['OPENAI_API_KEY'],
    npm: ['openai'],
    getUrl: 'https://platform.openai.com/api-keys',
    models: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'o3', 'o4-mini', 'codex-mini'],
    description: 'GPT & Codex models. Paid API.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    envKeys: ['ANTHROPIC_API_KEY'],
    npm: ['@anthropic-ai/sdk'],
    getUrl: 'https://console.anthropic.com/settings/keys',
    models: ['claude-sonnet-4-20250514', 'claude-opus-4-20250514', 'claude-haiku-3.5'],
    description: 'Claude models. Premium reasoning.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    envKeys: ['OPENROUTER_API_KEY'],
    npm: ['openai'],
    getUrl: 'https://openrouter.ai/keys',
    models: ['auto', 'anthropic/claude-sonnet-4', 'google/gemini-2.5-pro', 'deepseek/deepseek-r1'],
    description: 'Multi-model gateway. Access 200+ models with one key.',
  },
  {
    id: 'groq',
    name: 'Groq',
    envKeys: ['GROQ_API_KEY'],
    npm: ['groq-sdk'],
    getUrl: 'https://console.groq.com/keys',
    models: ['llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    description: 'Ultra-fast Llama/Mixtral inference. Free tier available.',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    envKeys: ['DEEPSEEK_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.deepseek.com/v1',
    getUrl: 'https://platform.deepseek.com/api_keys',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    description: 'DeepSeek V3/R1. Very cheap, strong coding.',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    envKeys: ['HF_TOKEN'],
    npm: ['openai'],
    endpoint: 'https://api-inference.huggingface.co/v1',
    getUrl: 'https://huggingface.co/settings/tokens',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    description: 'Open-source models. Free inference API.',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    envKeys: ['LM_STUDIO_URL'],
    npm: ['openai'],
    endpoint: 'http://localhost:1234/v1',
    defaultValue: 'http://localhost:1234/v1',
    models: ['local-model'],
    description: 'Run models locally via LM Studio. No API key needed.',
    noKeyRequired: true,
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    envKeys: ['OLLAMA_URL'],
    npm: ['openai'],
    endpoint: 'http://localhost:11434/v1',
    defaultValue: 'http://localhost:11434/v1',
    models: ['llama3.3', 'codellama', 'mistral', 'phi3'],
    description: 'Run models locally via Ollama. No API key needed.',
    noKeyRequired: true,
  },
  {
    id: 'alibaba',
    name: 'Alibaba Cloud (DashScope)',
    envKeys: ['DASHSCOPE_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    getUrl: 'https://dashscope.console.aliyun.com/apiKey',
    models: ['qwen-max', 'qwen-plus', 'qwen-turbo'],
    description: 'Qwen models from Alibaba.',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    envKeys: ['MINIMAX_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.minimax.chat/v1',
    getUrl: 'https://platform.minimaxi.com',
    models: ['abab6.5s-chat', 'abab5.5-chat'],
    description: 'MiniMax AI models.',
  },
  {
    id: 'kimi',
    name: 'Kimi / Moonshot',
    envKeys: ['KIMI_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.moonshot.cn/v1',
    getUrl: 'https://platform.moonshot.cn',
    models: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
    description: 'Moonshot/Kimi. Strong long-context.',
  },
  {
    id: 'zhipu',
    name: 'z.ai / GLM (Zhipu)',
    envKeys: ['GLM_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://open.bigmodel.cn/api/paas/v4',
    getUrl: 'https://open.bigmodel.cn',
    models: ['glm-4-plus', 'glm-4-flash', 'glm-4'],
    description: 'Zhipu GLM models.',
  },
  {
    id: 'arcee',
    name: 'Arcee AI',
    envKeys: ['ARCEEAI_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.arcee.ai/v1',
    getUrl: 'https://app.arcee.ai',
    models: ['arcee-agent', 'arcee-lite'],
    description: 'Arcee AI specialized models.',
  },
  {
    id: 'gmi',
    name: 'GMI Cloud',
    envKeys: ['GMI_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.gmi.ai/v1',
    getUrl: 'https://gmi.ai',
    models: ['gmi-default'],
    description: 'GMI Cloud inference.',
  },
  {
    id: 'tencent',
    name: 'Tencent TokenHub',
    envKeys: ['TOKENHUB_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.tokenhub.cloud/v1',
    getUrl: 'https://tokenhub.cloud',
    models: ['hunyuan-large', 'hunyuan-lite'],
    description: 'Tencent Hunyuan models.',
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi MiMo',
    envKeys: ['XIAOMI_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.mimo.xiaomi.com/v1',
    getUrl: 'https://mimo.xiaomi.com',
    models: ['mimo-default'],
    description: 'Xiaomi MiMo AI.',
  },
  {
    id: 'kilocode',
    name: 'Kilo Code',
    envKeys: ['KILOCODE_API_KEY'],
    npm: ['openai'],
    endpoint: 'https://api.kilocode.ai/v1',
    getUrl: 'https://kilocode.ai',
    models: ['kilo-default'],
    description: 'Kilo Code specialized coding models.',
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-Compatible Endpoint',
    envKeys: ['CUSTOM_API_KEY', 'CUSTOM_API_URL'],
    npm: ['openai'],
    models: ['custom'],
    description: 'Any OpenAI-compatible API. You provide the URL and key.',
    isCustom: true,
  },
];

// Tools / services that need API keys (non-model)
const SERVICES = [
  {
    id: 'tavily',
    name: 'Tavily Search',
    envKeys: ['TAVILY_API_KEY'],
    multiKey: true,
    maxKeys: 5,
    envPrefix: 'TAVILY_API_KEY_',
    npm: ['@tavily/core'],
    getUrl: 'https://app.tavily.com/home',
    description: 'Web search for agent research. Free tier: 1000 searches/month.',
  },
  {
    id: 'telegram',
    name: 'Telegram Bot',
    envKeys: ['TELEGRAM_BOT_TOKEN'],
    npm: ['telegram'],
    getUrl: 'https://t.me/BotFather',
    description: 'Connect EterX to Telegram.',
  },
  {
    id: 'slack',
    name: 'Slack Integration',
    envKeys: ['SLACK_ACCESS_TOKEN', 'SLACK_CLIENT_ID', 'SLACK_CLIENT_SECRET'],
    npm: ['@slack/bolt', '@slack/web-api'],
    getUrl: 'https://api.slack.com/apps',
    description: 'Connect EterX to Slack workspace.',
  },
];

module.exports = { PROVIDERS, SERVICES };
